# Generated by Django 4.2.28 on 2026-02-24 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorystats',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='assets.category'),
        ),
        migrations.AlterUniqueTogether(
            name='categorystats',
            unique_together={('category', 'date')},
        ),
    ]
