# Generated by Django 4.2.28 on 2026-02-24 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assetimage',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.category'),
        ),
        migrations.AddField(
            model_name='asset',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status', 'category'], name='assets_asse_status_35fdfb_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['latitude', 'longitude'], name='assets_asse_latitud_0c42dc_idx'),
        ),
    ]
